
name: Node CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.17.0
      uses: actions/setup-node@v1
      with:
        node-version: 10.17.0
    - name: Install & lint
      run: |
        npm install
        npm run lint
    - name: Unit tests
      run: npm run test
    - name: Cypress tests
      run: npm run cypress:CI
    - name: Build
      run: npm run build --if-present
    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_CLOUDFRONT_DIST_ID: ${{ secrets.AWS_CLOUDFRONT_DIST_ID }}
      run: node ./deploy-scripts/deploy.js